# One Dark

# Colors
# bg:      #282c34
# bar:     #3b4048
# fg:      #abb2bf
# blue:    #61afef
# green:   #98c379
# yellow:  #e5c07b
# gray:    #5c6370

set -g status-position bottom
set -g status-style "bg=#3b4048,fg=#abb2bf"

# Session
set -g status-left "#[fg=#98c379,bold] #S "

# Right
# set -g status-right "#[fg=#61afef]#{user}@#{host} #[fg=#3e4452]| #[fg=#98c379]%H:%M #[fg=#e5c07b]%Y-%m-%d #(date +"UTC%:z")"
set -g status-right "#[fg=#98c379]#(date +"UTC%:::z") #[fg=#e5c07b]%Y-%m-%d %H:%M"

# Windows
set -g window-status-format " #I:#W "
set -g window-status-style "bg=#3b4048,fg=#abb2bf"

# Active window
set -g window-status-current-format " #I:#W "
set -g window-status-current-style "bg=#61afef,fg=#282c34,bold"

set -g window-status-separator ""

# Panes
set -g pane-border-style "fg=#5c6370"
set -g pane-active-border-style "fg=#61afef"

# Messages / copy mode
set -g message-style "bg=#61afef,fg=#282c34"
set -g mode-style "bg=#61afef,fg=#282c34"
