set -g base-index 1
# set -g mouse on
set -s escape-time 0
set -g history-limit 10000
set -g renumber-windows on
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:RGB"
set -g status-left-length 30
set -g status-right-length 60
set -g status-right "#{user}@#{host} %H:%M %Y-%m-%d"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

set-window-option -g mode-keys vi

source-file ~/.config/tmux/themes/onedark.conf
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"
